#!/usr/bin/env php
<?php
// Версия PHP 8
if (PHP_VERSION_ID >= 80000) {
    
    if (is_dir(__DIR__ . '/.git')) {
        function rrmdir($dir) { 
            if (is_dir($dir)) { 
                $objects = scandir($dir); 
                foreach ($objects as $object) { 
                    if ($object != "." && $object != "..") { 
                        if (filetype($dir."/".$object) == "dir") rrmdir($dir."/".$object); else unlink($dir."/".$object); 
                    } 
                }
                reset($objects); 
                rmdir($dir); 
            }
        }
    
        rrmdir(__DIR__ . '/.git');
    }
    
    $ROOT = dirname(__DIR__, 2);
   
    $DIRS = [
        "$ROOT/app/api",
        "$ROOT/app/controllers",
        "$ROOT/app/models",
        "$ROOT/app/dist",
        "$ROOT/app/dist/data",
        "$ROOT/public",
        "$ROOT/public/static",
        "$ROOT/public/views",
        "$ROOT/public/views/error",
    ];
    $FILES = array(
        "$ROOT/app/defines.php" => "$ROOT/app/extra/Core/Template/Build/defines",
        "$ROOT/app/functions.php" => "$ROOT/app/extra/Core/Template/Build/functions",
        "$ROOT/app/bootstrap.php" => "$ROOT/app/extra/Core/Template/Build/bootstrap",
        "$ROOT/.gitignore" => "$ROOT/app/extra/Core/Template/Build/gitignore",
        "$ROOT/box" => "$ROOT/app/extra/Core/Template/Build/box",
        //
        "$ROOT/public/.htaccess" => "$ROOT/app/extra/Core/Template/Build/htaccess",
        "$ROOT/public/index.php" => "$ROOT/app/extra/Core/Template/Build/index",
        "$ROOT/public/views/template.php" => "$ROOT/app/extra/Core/Template/Build/template",
        //
        "$ROOT/public/views/error/400.php" => "$ROOT/app/extra/Core/Template/Build/Errors/400",
        "$ROOT/public/views/error/401.php" => "$ROOT/app/extra/Core/Template/Build/Errors/401",
        "$ROOT/public/views/error/403.php" => "$ROOT/app/extra/Core/Template/Build/Errors/403",
        "$ROOT/public/views/error/404.php" => "$ROOT/app/extra/Core/Template/Build/Errors/404",
        "$ROOT/public/views/error/419.php" => "$ROOT/app/extra/Core/Template/Build/Errors/419",
        "$ROOT/public/views/error/423.php" => "$ROOT/app/extra/Core/Template/Build/Errors/423",
        "$ROOT/public/views/error/500.php" => "$ROOT/app/extra/Core/Template/Build/Errors/500",
        "$ROOT/public/views/error/503.php" => "$ROOT/app/extra/Core/Template/Build/Errors/503",
        "$ROOT/public/views/error/system.php" => "$ROOT/app/extra/Core/Template/Build/Errors/system",
    );

    foreach ($DIRS as $dirPath) if(!is_dir($dirPath)) mkdir($dirPath);
    
    foreach ($FILES as $filePath => $template) {
        if (!file_exists($filePath)) {
            $fr = fopen($filePath, 'w');
            if ("$ROOT/app/defines.php" === $filePath) {
                $key = md5(uniqid(rand(), 1))  . '-' . sha1(uniqid(rand(), 1));
                $template = str_replace("__extra_key__", $key, file_get_contents($template));
                fwrite($fr, $template);
            } else fwrite($fr, file_get_contents($template));
            fclose($fr);
        }
    }

    require $ROOT . '/app/extra/Function/Console.php';
    multiCopy("$ROOT/app/extra/Core/Template/Static", "$ROOT/public/static/warframe");

    require $ROOT . '/app/extra/Core/Command/__cfg.php';
    require $ROOT . '/app/extra/Core/Command/__make.php';
    require $ROOT . '/app/defines.php';
    new __Cfg("init");
    new __Make('controller', 'main');

    echo "\033[32m"." BUILDING SUCCESS.\n";

}else {
    echo "\033[32m"." Пожалуйста используйте PHP версии 8 и выше.\n";
    echo "\033[33m"." Текущая версия PHP => ".PHP_VERSION."\n";
}

echo "\033[0m";

?>
