#!/usr/bin/env php
<?php
// Версия PHP 8.1
if (PHP_VERSION_ID >= 80100) {

    if (is_dir(__DIR__ . '/.git')) {
        echo "\033[33m"." *** WARNING *** Please delete the folder \".git\": rm -R " .
            __DIR__ .
            "/.git \n";
    }
    
    $ROOT = dirname(__DIR__, 2);

    $DIRS = [
        "$ROOT/app/Apis",
        "$ROOT/app/Controllers",
        "$ROOT/app/Libs",
        "$ROOT/app/Models",
        "$ROOT/app/Repositories",
        "$ROOT/app/Resources",
        "$ROOT/app/Resources/exception",
        "$ROOT/app/Services",
        "$ROOT/public",
        "$ROOT/public/media",
        "$ROOT/public/static",
        "$ROOT/storage/cache",
        "$ROOT/storage/logs",
    ];
    foreach ($DIRS as $dirPath) if(!is_dir($dirPath)) mkdir($dirPath);


    $FILES = array(
        // app
        "$ROOT/app/.env" => "$ROOT/app/Extra/Core/Template/Build/app/env",
        "$ROOT/app/bootstrap.php" => "$ROOT/app/Extra/Core/Template/Build/app/bootstrap",
        "$ROOT/app/constants.php" => "$ROOT/app/Extra/Core/Template/Build/app/constants",
        "$ROOT/app/database.php" => "$ROOT/app/Extra/Core/Template/Build/app/database",
        "$ROOT/app/defines.php" => "$ROOT/app/Extra/Core/Template/Build/app/defines",
        "$ROOT/app/functions.php" => "$ROOT/app/Extra/Core/Template/Build/app/functions",
        // app => resource
        "$ROOT/app/Resources/template.php" => "$ROOT/app/Extra/Core/Template/Build/app/resource/template",
        "$ROOT/app/Resources/exception/system.php" => "$ROOT/app/Extra/Core/Template/Build/app/resource/error",
        // public
        "$ROOT/public/.htaccess" => "$ROOT/app/Extra/Core/Template/Build/htaccess",
        "$ROOT/public/index.php" => "$ROOT/app/Extra/Core/Template/Build/index",
        // git =>  gitignore
        "$ROOT/.gitignore" => "$ROOT/app/Extra/Core/Template/Build/git/git/ignores/root",
        "$ROOT/public/media/.gitignore" => "$ROOT/app/Extra/Core/Template/Build/media",
        "$ROOT/storage/.gitignore" => "$ROOT/app/Extra/Core/Template/Build/storage",
        "$ROOT/storage/cache/.gitignore" => "$ROOT/app/Extra/Core/Template/Build/storageCache",
        "$ROOT/storage/logs/.gitignore" => "$ROOT/app/Extra/Core/Template/Build/storageLogs",
        // root
        "$ROOT/box" => "$ROOT/app/Extra/Core/Template/Build/box",
    );
    foreach ($FILES as $filePath => $template) {
        if (!file_exists($filePath)) {
            $fr = fopen($filePath, 'w');
            if ("$ROOT/app/defines.php" === $filePath) {
                $key = md5(uniqid(rand(), 1))  . '-' . sha1(uniqid(rand(), 1));
                $template = str_replace("__extra_key__", $key, file_get_contents($template));
                fwrite($fr, $template);
            } else fwrite($fr, file_get_contents($template));
            fclose($fr);
        }
    }

    require $ROOT . '/app/Extra/Function/Console.php';
    multiCopy("$ROOT/app/Extra/Core/Template/Static", "$ROOT/public/static/warframe");
    echo "\033[32m"." BUILDING SUCCESS.\n";

} else {
    echo "\033[32m"." Пожалуйста используйте PHP версии 8 и выше.\n";
    echo "\033[33m"." Текущая версия PHP => ".PHP_VERSION."\n";
}

echo "\033[0m";

?>
