version: '3.8'

networks:
  network:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - network
    volumes:
      - ./:/var/www/html/